import type { Socio } from '@/lib/types/socio'

export function mapSocioRow(row: Record<string, unknown>): Socio {
    return {
        id: row.IdSocio as number,
        nome: (row.Nome as string) ?? null,
        rg: (row.RG as string) ?? null,
        emissor: (row.Emissor as string) ?? null,
        cpf: (row.CPF as string) ?? null,
        nascimento: (row.Nascimento as string) ?? null,
        sexo: (row.Sexo as string) ?? null,
        naturalidade: (row.Naturalidade as string) ?? null,
        naturalidadeUF: (row.NaturalidadeUF as string) ?? null,
        nacionalidade: (row.Nacionalidade as string) ?? null,
        estadoCivil: (row.EstadoCivil as string) ?? null,
        endereco: (row.Endereco as string) ?? null,
        complemento: (row.Complemento as string) ?? null,
        bairro: (row.Bairro as string) ?? null,
        cep: (row.CEP as string) ?? null,
        celular: (row.Celular as string) ?? null,
        redeSocial: (row.RedeSocial as string) ?? null,
        pai: (row.Pai as string) ?? null,
        mae: (row.Mae as string) ?? null,
        dataCadastro: (row.DataCadastro as string) ?? null,
        cadastrante: (row.Cadastrante as string) ?? null,
        status: (row.Status as string) ?? null,
        matricula: (row.Matricula as string) ?? null,
        dataMensalidade: (row.DataMensalidade as string) ?? null,
        valorMensalidade: (row.ValorMensalidade as number) ?? null,
        dataAdmissao: (row.DataAdmissao as string) ?? null,
        ctps: (row.CTPS as string) ?? null,
        funcao: (row.Funcao as string) ?? null,
        codEmpresa: (row.CodEmpresa as string) ?? null,
        cnpj: (row.CNPJ as string) ?? null,
        razaoSocial: (row.RazaoSocial as string) ?? null,
        nomeFantasia: (row.NomeFantasia as string) ?? null,
        dataDemissao: (row.DataDemissao as string) ?? null,
        motivoDemissao: (row.MotivoDemissao as string) ?? null,
        carta: (row.Carta as boolean) ?? null,
        carteira: (row.Carteira as boolean) ?? null,
        ficha: (row.Ficha as boolean) ?? null,
        observacao: (row.Observacao as string) ?? null,
        telefone: (row.Telefone as string) ?? null,
        empresa: (row.NomeFantasia as string) ?? (row.RazaoSocial as string) ?? null,
        setor: (row.Setor as string) ?? null,
    }
}
